"""
doc_writer.py
---------------------------------------

Creates a professionally formatted DOCX
from the generated chapters.
"""

import os
import re
from datetime import datetime

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor


class DocumentWriter:

    def __init__(self, output_folder="outputs"):

        self.output_folder = output_folder

        os.makedirs(
            self.output_folder,
            exist_ok=True
        )

    # -------------------------------------------------------
    # Helpers
    # -------------------------------------------------------

    def sanitize_filename(self, text):

        text = re.sub(
            r'[^a-zA-Z0-9_\- ]',
            '',
            text
        )

        text = text.strip().replace(" ", "_")

        if len(text) == 0:
            text = "Book"

        return text[:80]

    def clean_text(self, text):

        text = text.replace("\r", "")

        lines = []

        for line in text.split("\n"):

            line = line.strip()

            if line:

                lines.append(line)

        return lines

    # -------------------------------------------------------
    # Formatting
    # -------------------------------------------------------

    def apply_default_style(self, doc):

        normal = doc.styles["Normal"]

        normal.font.name = "Calibri"

        normal.font.size = Pt(12)

    # -------------------------------------------------------
    # Cover Page
    # -------------------------------------------------------

    def add_cover(self, doc, topic):

        p = doc.add_paragraph()

        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = p.add_run(topic)

        run.bold = True

        run.font.size = Pt(30)

        run.font.color.rgb = RGBColor(
            20,
            20,
            20
        )

        doc.add_paragraph()

        p = doc.add_paragraph()

        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = p.add_run(
            "Generated using Knifork AI"
        )

        run.italic = True

        run.font.size = Pt(16)

        doc.add_paragraph()

        p = doc.add_paragraph()

        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = p.add_run(
            datetime.now().strftime(
                "%d %B %Y"
            )
        )

        run.font.size = Pt(12)

        doc.add_page_break()

    # -------------------------------------------------------
    # Table of Contents
    # -------------------------------------------------------

    def add_toc(
        self,
        doc,
        chapters
    ):

        heading = doc.add_heading(
            "Table of Contents",
            level=1
        )

        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        for chapter in chapters:

            doc.add_paragraph(

                f"Chapter {chapter['chapter']} - {chapter['title']}"

            )

        doc.add_page_break()

    # -------------------------------------------------------
    # Chapters
    # -------------------------------------------------------

    def add_chapter(
        self,
        doc,
        chapter
    ):

        heading = doc.add_heading(

            f"Chapter {chapter['chapter']} : {chapter['title']}",

            level=1

        )

        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        lines = self.clean_text(

            chapter["content"]

        )

        for line in lines:

            # Markdown Heading #

            if line.startswith("# "):

                doc.add_heading(

                    line[2:].strip(),

                    level=2

                )

                continue

            if line.startswith("## "):

                doc.add_heading(

                    line[3:].strip(),

                    level=3

                )

                continue

            if line.startswith("### "):

                doc.add_heading(

                    line[4:].strip(),

                    level=4

                )

                continue

            para = doc.add_paragraph()

            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

            para.add_run(line)

        doc.add_page_break()

    # -------------------------------------------------------
    # Footer
    # -------------------------------------------------------

    def add_footer(self, doc):

        section = doc.sections[0]

        footer = section.footer

        p = footer.paragraphs[0]

        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = p.add_run(

            "Generated by Knifork AI"

        )

        run.italic = True

        run.font.size = Pt(10)

    # -------------------------------------------------------
    # Build DOCX
    # -------------------------------------------------------

    def create_document(

        self,

        topic,

        chapters

    ):

        filename = self.sanitize_filename(

            topic

        )

        filepath = os.path.join(

            self.output_folder,

            filename + ".docx"

        )

        doc = Document()

        self.apply_default_style(doc)

        self.add_cover(

            doc,

            topic

        )

        self.add_toc(

            doc,

            chapters

        )

        for chapter in chapters:

            self.add_chapter(

                doc,

                chapter

            )

        self.add_footer(

            doc

        )

        doc.save(

            filepath

        )

        return filepath